/**
 * Content Strings, Emails, and URLs
 * Centralized content for easy localization and updates
 */

// Application Info
export const APP_INFO = {
  NAME: 'UsernameSearch.io',
  URL: 'https://usernamesearch.io',
  DESCRIPTION: 'Check username availability across 500+ platforms instantly',
} as const;

// Export File Names
export const EXPORT_FILENAMES = {
  JSON: (username: string) => `username-search-${username}-${Date.now()}.json`,
  CSV: (username: string) => `username-search-${username}-${Date.now()}.csv`,
  MARKDOWN: (username: string) => `username-search-${username}-${Date.now()}.md`,
} as const;

// Export Content
export const EXPORT_CONTENT = {
  CSV_HEADERS: ['Platform', 'Status', 'Category', 'URL'],
  STATUS_AVAILABLE: 'Available',
  STATUS_TAKEN: 'Taken',
  ICON_AVAILABLE: '✅',
  ICON_TAKEN: '❌',
} as const;

// AI Generation Styles
export const AI_STYLES = {
  creative: 'Be imaginative and unique, mixing words in unexpected ways',
  professional: 'Keep it business-appropriate and trustworthy',
  casual: 'Make it friendly and approachable',
  gaming: 'Create something that sounds cool for gaming platforms',
  tech: 'Use tech-related terms and make it sound innovative',
  artistic: 'Make it sound creative and expressive',
} as const;

// Platform-specific prompts for AI generation
export const PLATFORM_PROMPTS: Record<string, string> = {
  instagram: 'Create Instagram-friendly usernames that are catchy and memorable',
  tiktok: 'Generate fun, trendy usernames perfect for TikTok',
  twitter: 'Make professional yet engaging usernames for Twitter',
  linkedin: 'Create professional, business-appropriate usernames',
  github: 'Generate developer-friendly usernames for GitHub',
  gaming: 'Create cool, edgy usernames for gaming platforms',
  youtube: 'Make memorable usernames perfect for content creators',
} as const;

// Fallback Generation Patterns
export const FALLBACK_PATTERNS = {
  PREFIXES: {
    creative: ['artistic', 'magic', 'dream', 'mystic', 'epic'],
    professional: ['pro', 'expert', 'ace', 'prime', 'elite'],
    gaming: ['game', 'pro', 'epic', 'legend', 'master'],
    tech: ['dev', 'code', 'tech', 'cyber', 'digital'],
    casual: ['cool', 'fun', 'nice', 'happy', 'chill'],
    artistic: ['art', 'creative', 'design', 'paint', 'sketch'],
  },
  SUFFIXES: {
    creative: ['x', '2024', 'pro', 'star', 'dream'],
    professional: ['pro', 'expert', '2024', 'official', 'biz'],
    gaming: ['gamer', 'pro', 'x', 'legend', 'master'],
    tech: ['dev', 'tech', 'code', 'byte', 'bit'],
    casual: ['cool', 'fun', 'awesome', 'nice', 'great'],
    artistic: ['art', 'creative', 'studio', 'design', 'gallery'],
  },
} as const;

// Error Messages
export const ERROR_MESSAGES = {
  USERNAME_REQUIRED: 'Username is required',
  USERNAME_MIN_LENGTH: (min: number) => `Username must be at least ${min} characters long`,
  USERNAME_MAX_LENGTH: (max: number) => `Username must be less than ${max} characters`,
  REQUEST_TIMEOUT: 'Request timeout',
  UNKNOWN_ERROR: 'Unknown error occurred',
  INVALID_USERNAME_FORMAT: 'Invalid username format for this site',
  API_KEY_INVALID_FORMAT: 'Invalid API key format',
  API_KEY_NOT_FOUND: 'API key not found',
  API_KEY_SUSPENDED: (status: string) => `API key is ${status}`,
  API_KEY_EXHAUSTED: 'API key credits exhausted',
} as const;

// Validation Messages
export const VALIDATION_MESSAGES = {
  NO_CANDIDATES: 'No response from Gemini API',
  AI_GENERATION_FAILED: 'AI generation failed, using fallback method',
  INVALID_REGEX: (regex: string) => `Invalid regex for site: ${regex}`,
} as const;

// Health Check Messages
export const HEALTH_MESSAGES = {
  AI_HEALTHY: 'AI generator is working properly',
  AI_UNHEALTHY_NO_RESULTS: 'AI generator returned no results',
} as const;

// Share URL
export const SHARE_URL = {
  BASE: 'https://usernamesearch.io/share',
  PARAM_USERNAME: 'u',
  PARAM_AVAILABLE: 'a',
  PARAM_TAKEN: 't',
  PARAM_TIMESTAMP: 'ts',
} as const;

// Markdown Export Template
export const MARKDOWN_TEMPLATE = {
  HEADER: (username: string) => `# Username Search Results: @${username}`,
  SUMMARY: (total: number, available: number, taken: number, timestamp: string) => `## Summary
- **Date**: ${timestamp}
- **Total Platforms Checked**: ${total}
- **Available**: ${available} ✅
- **Taken**: ${taken} ❌`,
  AVAILABLE_SECTION: (count: number) => `## Available Platforms (${count})`,
  TAKEN_SECTION: (count: number) => `## Taken Platforms (${count})`,
  TABLE_HEADER: '| Platform | Category | URL |\n|----------|----------|-----|',
  TABLE_ROW_AVAILABLE: (source: string, category: string | undefined, url: string) =>
    `| ${source} | ${category || 'N/A'} | [Check](${url}) |`,
  TABLE_ROW_TAKEN: (source: string, category: string | undefined, url: string) =>
    `| ${source} | ${category || 'N/A'} | [View](${url}) |`,
  FOOTER: `---
*Generated by [UsernameSearch.io](https://usernamesearch.io)*`,
} as const;

// Site Categories
export const SITE_CATEGORIES = {
  DEFAULT: 'Other',
} as const;

// API Key Status
export const API_KEY_STATUS = {
  ACTIVE: 'active',
  EXPIRED: 'expired',
  SUSPENDED: 'suspended',
} as const;
