import { SearchResult } from '@/types'

export interface ExportData {
  username: string
  timestamp: string
  totalChecked: number
  totalAvailable: number
  totalTaken: number
  results: SearchResult[]
}

/**
 * Export search results as JSON
 */
export function exportAsJSON(data: ExportData): void {
  const jsonString = JSON.stringify(data, null, 2)
  const blob = new Blob([jsonString], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `username-search-${data.username}-${Date.now()}.json`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export search results as CSV
 */
export function exportAsCSV(data: ExportData): void {
  const headers = ['Platform', 'Status', 'Category', 'URL']
  const rows = data.results.map(result => [
    result.source,
    result.isExist ? 'Taken' : 'Available',
    result.category || '',
    result.url
  ])
  
  const csvContent = [
    `Username Search Results for: ${data.username}`,
    `Date: ${data.timestamp}`,
    `Total Checked: ${data.totalChecked}`,
    `Available: ${data.totalAvailable}`,
    `Taken: ${data.totalTaken}`,
    '',
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n')
  
  const blob = new Blob([csvContent], { type: 'text/csv' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `username-search-${data.username}-${Date.now()}.csv`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export search results as Markdown
 */
export function exportAsMarkdown(data: ExportData): void {
  const availableResults = data.results.filter(r => !r.isExist)
  const takenResults = data.results.filter(r => r.isExist)
  
  const markdownContent = `# Username Search Results: @${data.username}

## Summary
- **Date**: ${data.timestamp}
- **Total Platforms Checked**: ${data.totalChecked}
- **Available**: ${data.totalAvailable} ✅
- **Taken**: ${data.totalTaken} ❌

## Available Platforms (${availableResults.length})

| Platform | Category | URL |
|----------|----------|-----|
${availableResults.map(r => `| ${r.source} | ${r.category || 'N/A'} | [Check](${r.url}) |`).join('\n')}

## Taken Platforms (${takenResults.length})

| Platform | Category | URL |
|----------|----------|-----|
${takenResults.map(r => `| ${r.source} | ${r.category || 'N/A'} | [View](${r.url}) |`).join('\n')}

---
*Generated by [UsernameSearch.io](https://usernamesearch.io)*
`
  
  const blob = new Blob([markdownContent], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `username-search-${data.username}-${Date.now()}.md`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Copy results to clipboard
 */
export function copyToClipboard(data: ExportData): Promise<boolean> {
  const text = data.results
    .map(r => `${r.source}: ${r.isExist ? '❌ Taken' : '✅ Available'}`)
    .join('\n')
  
  const summary = `Username Search Results for @${data.username}
Total: ${data.totalChecked} | Available: ${data.totalAvailable} | Taken: ${data.totalTaken}

${text}`
  
  return navigator.clipboard.writeText(summary)
    .then(() => true)
    .catch(() => false)
}

/**
 * Generate shareable URL with results
 */
export function generateShareURL(username: string, results: SearchResult[]): string {
  const baseURL = 'https://usernamesearch.io/share'
  const available = results.filter(r => !r.isExist).length
  const taken = results.filter(r => r.isExist).length
  
  const params = new URLSearchParams({
    u: username,
    a: available.toString(),
    t: taken.toString(),
    ts: Date.now().toString()
  })
  
  return `${baseURL}?${params.toString()}`
}

/**
 * Export search results in the specified format
 */
export function exportResults(
  format: 'json' | 'csv' | 'markdown',
  username: string,
  results: SearchResult[],
  stats: {
    totalChecked: number
    totalAvailable: number
    totalTaken: number
  }
): void {
  const exportData: ExportData = {
    username,
    timestamp: new Date().toISOString(),
    totalChecked: stats.totalChecked,
    totalAvailable: stats.totalAvailable,
    totalTaken: stats.totalTaken,
    results
  }
  
  switch (format) {
    case 'json':
      exportAsJSON(exportData)
      break
    case 'csv':
      exportAsCSV(exportData)
      break
    case 'markdown':
      exportAsMarkdown(exportData)
      break
    default:
      console.error(`Unsupported export format: ${format}`)
  }
}